version: '3.9'
services:
  api:
    container_name: viva_api
    restart: on-failure
    build:
      context: ./app
      dockerfile: ../Dockerfile
      target: base
    image: node_vivatech
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/nodemon.json:/home/node/app/nodemon.json
    env_file:
      - .env
    ports:
      - '4000:4000'
      - '9229:9229'
    command: yarn run dev