name: Lint / Tests
on:
  pull_request:
    branches:
      - "*"

env:
  NODE_VERSION: 16
  ACCESS_TOKEN_SECRET: "ZzpPypwUKQiCLra6h72ny8DemduUwQbg"
  REFRESH_TOKEN_SECRET: "7tQKTPn8LcZowxVUAMj43v4rmgQjzmu7JCeG"

jobs:

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: yarn

      - name: Code Linting
        run: yarn lint

  tests:
    name: Run jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: yarn

      - name: Code Linting
        run: yarn test:verbose
